---
ee_list:
  - name: custom_ee_image
    description: Custom EE image supporting Azure and GCP
    tags:
      - "{{ ee_image_tag }}"
      - latest
    images:
      base_image:
        name: "{{ ee_base_image }}"
        # name: "{{ aap_hostname | ansible.builtin.urlsplit('hostname') }}/ee-minimal-rhel9:latest"
    options:
      package_manager_path: /usr/bin/microdnf
    dependencies:
      python_interpreter:
        python_path: /usr/bin/python3.12
      system:
        - gcc
        - python3.12-devel
        - systemd-devel
      python:
        - azure-cli
        - azure-mgmt-recoveryservices
        - azure-mgmt-recoveryservicesbackup
        - azure-schemaregistry-avroserializer
        - azure-eventhub
        - firewall
        - gspread
        - gspread-pandas
        - google-auth-httplib2
        - hvac
        - terrasnek

...
